### ISSUE TITLE
Error in DynamicCyclicQueue

### ISSUE THREAD

**Issue by chdh** [kleinron/lite-fifo#4]
The program logic in `DynamicCyclicQueue._normalizeToZeroIndex()` using `swap()` is wrong.

Test case::

```
const {DynamicCyclicQueue} = require("lite-fifo");

function test1() {
   const q = new DynamicCyclicQueue(5);
   for (let i = 0; i < 3; i++) {
      q.enqueue(99);
   }
   for (let i = 1; i <= 5; i++) {
      if (q.size() == 5) {
         q.dequeue();
      }
      q.enqueue(i);
   }
   q.enqueue(6);
   while (q.size()) {
      console.log(q.dequeue());
   }
}

test1();

```
Expected output: 1, 2, 3, 4, 5, 6
Effective output: 5, 6, 4, 2, 1, null

This is a nice package and I appreciate the comparism and description of the different FIFO implementations. But I recommend writing a stress test with random behavior to verify the correctness of the implementation.

**Comment by kleinron** [comment]
thanks for the feedback, I'll fix it shortly!

**Comment by kleinron** [comment]
@chdh as promised, a fix was published.
I followed your recommendations and added stress tests.
Your feedback is appreciated. Thanks!
